version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    depends_on:
      - db
    restart: always
    ports:
      - '4466:4466'
    networks:
     - db
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: ${POSTGRES_HOST}
            port: ${POSTGRES_PORT}
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
            ssl: ${POSTGRES_SSL}
            database: ${POSTGRES_DATABASE}
            connectionLimit: ${POSTGRES_CONNECTION_COUNT}
            migrations: true
            managementSchema: management

  db:
    image: postgres:9.6
    environment:
      - "PGDATA=/var/lib/postgresql/data/pgdata"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - 5432:5432
    networks:
      - db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379

networks:
  db:
    driver: bridge

volumes:
  db_data:
